name: EdgeWARN
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pyyaml
  - aioboto3
  - affine
  - boto3
  - cfgrib
  - numpy
  - netcdf4
  - rioxarray
  - scikit-image
  - scipy
  - shapely
  - rasterio
  - xarray
  - pyproj
  - proj
  - psutil
  - ijson
  - ruamel.yaml
  - textual
  - pip:
    - gputil
    - pytest
    - pytest-mock
    - pytest-asyncio
    - aiofiles
    - aiohttp
    - requests
    - beautifulsoup4
    - opencv-python-headless
